### PR TITLE
Added simple examples to README

### PR DESCRIPTION
**Pull request by d4rkd0s**
Added simple examples for fast recognition of how Chinook works, and also added some simple titles to sections on the readme.

### CODE REVIEW

**Comment by d4rkd0s** [comment]
@pshannon-bioc when you get a chance can you take a look at this. Plz n thx! :+1:

**Comment by d4rkd0s** [comment]
@LisaMc or @pshannon-bioc can someone take a look at this?

Please and thanks :+1:

**Comment by d4rkd0s** [comment]
So this has been sitting for more than a month closing it... 😞

**Comment by LisaMc** [comment]
@d4rkd0s just seeing this.  Sorry for the slow response.  Most of Oncoscape dev is happening on a different repo: https://github.com/FredHutch/Oncoscape, and we'd appreciate your help and feedback there.

**Comment by d4rkd0s** [comment]
@LisaMc so the Chinook protocol is developed over inside the Oncoscape repository?

**Comment by LisaMc** [comment]
@d4rkd0s Oncoscape has undergone a major refactor this past year and we have adopted a REST api for data transfer. We're pulling together the documentation [here](http://resources.sttrcancer.org/api/#introduction)  @pshannon-bioc uses the Chinook protocol on some other interesting projects and is the person to talk with about updates and implementation.

**Comment by d4rkd0s** [comment]
@LisaMc sounds good ty! I'll look into some development work on Oncoscape

**Pull request closed without merging**
